# Generated by Django 4.0.6 on 2022-07-26 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('img', models.ImageField(default='uploads/No_image_available.svg.png', upload_to='uploads/')),
                ('discription', models.CharField(max_length=200, null='False')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, null='False', validators=[django.core.validators.MinValueValidator(limit_value=1)])),
            ],
        ),
        migrations.DeleteModel(
            name='Auctions',
        ),
    ]
