# Generated by Django 4.0.6 on 2022-07-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctions_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='pic',
            field=models.ImageField(default='./loona_pic.JPG', upload_to=''),
        ),
    ]
