# Generated by Django 4.0.6 on 2022-07-26 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_user_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('auction', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='commented_on', to='auctions.auction')),
                ('user_comment', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_comm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
