# Generated by Django 4.0.6 on 2022-07-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_auctions_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='pic',
            field=models.ImageField(default='./loona_pic.JPG', upload_to='uploads/'),
        ),
    ]
