# Generated by Django 4.0.6 on 2022-07-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='pic',
            field=models.ImageField(blank='True', null='True', upload_to='uploads/'),
        ),
    ]
