# Generated by Django 4.0.6 on 2022-07-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='pic',
        ),
        migrations.AddField(
            model_name='auction',
            name='discription',
            field=models.CharField(max_length=200, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='auction',
            name='img',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='auction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null='False'),
            preserve_default='False',
        ),
    ]
