# Generated by Django 4.0.6 on 2022-07-26 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_watchlist_auctions_watchlist_auctions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auctions',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.auction'),
        ),
    ]
