# Generated by Django 4.0.6 on 2022-07-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auction_pic_auction_discription_auction_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='img',
            field=models.ImageField(null='True', upload_to='uploads/'),
        ),
    ]
