# Generated by Django 4.0.6 on 2022-07-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='img',
            field=models.ImageField(blank=True, default='uploads/No_image_available.svg.png', upload_to='uploads/'),
        ),
    ]
