# Generated by Django 4.0.6 on 2022-07-26 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auction_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='img',
            field=models.ImageField(default='uploads/No_image_available.svg.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null='False', validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
