# Generated by Django 4.0.6 on 2022-07-27 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_value',
            new_name='Bid',
        ),
    ]
