# Generated by Django 4.0.6 on 2022-07-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, choices=[('Toys', 'Toys'), ('Home', 'Home')], max_length=20, null=True),
        ),
    ]
