# Generated by Django 4.0.6 on 2022-07-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, choices=[('Toys', 'Toys'), ('Home', 'Home'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Automotive', 'Automotive'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
